---
title: "Species Composition Model Details"
author: "Paul van Dam-Bates"
date: last-modified
output: rmarkdown::html_vignette
description: >
  Techincal details for how the species composition model works.
format: 
  html:
    embed-resources: true
    theme: cosmo
vignette: >
  %\VignetteIndexEntry{Custom HTML Vignette}
  %\VignetteEngine{quarto::format}
  %\VignetteEncoding{UTF-8}
---

## Data Types

### Hydroacoustic Counts

At Mission, every hour hydroacoustic counts are taken at each distance (0-50 m), aim, and bank using an ARIS 1800. The right bank is relatively flat and a single aim with no roll is sufficient for full coverage. However, on the left bank, two aims are used within the first 10 m to enumerate all fish. Counts are labelled as "Up" and "Down" for the number of fish counted as swimming upstream or down stream. Total salmon then is the number of fish migrating upriver, accounting for potential double counts by subtracting the down stream counts. The counts also inform the stratification weights from the stratified length measurements which we will describe next.

```{mermaid}
flowchart TD
  A(Hydroacoustic Counts) --> B(Total Salmon)
  A --> C(Stratification Weights)
```

### Hydroacoustic Lengths

At Mission, hydroacoustic lengths are taken for 20 fish, every three hours in each sonar Aim, Bin, and Bank. Sonar bins 1-3 are measured; distances further than that unreliable for length measurement. Updates to the sampling protocols will be trialed in 2026. Due to beam spreading, bin 3 will no longer be measured with effort distributed across the closer bins to improve precision.

A randomly chosen fish migrating past the monitoring station does not have an equal chance of being measured. Instead, due to the stratified design, fish that correspond to a high migration period are less likely to be observed than those in low migration. If 20 fish pass by and 20 are measured, then they are all measured with certainty (a census). If 100 fish pass by in the same period, and 20 are selected, then they are measured with probability 20/100. The number of fish that are passing by are measured during the corresponding sonar count ($N_i$). The inclusion probability $\gamma_i = n_i/N_i$, where $n_i$ is the number of lengths taken, generally 20.

```{mermaid}
flowchart TD
  A(Hydroacoustic Counts) --> B(Total Salmon)
  A --> C(Stratification Weights)
  C --> D(Hydroacoustic Lengths)
```

### Hydroacoustic Lengths

At Mission, the Whonnock test fishery operates just downstream of the site. A gillnet does two sets at the daytime high tide (targets the larger tide) for 30 minutes each. The number of sockeye, pink salmon, jack Chinook and adult Chinook are counted as either gilled or tangled. Additionally, fork lengths are also recorded. DFO also operates a Chinook focused fishery at Albion that also does two sets, changing the net type every day between a Chinook net constructed using 8 inch mesh and a multi-panel net consisting of panels of 6, 7, 8, and 9 inch mesh, similar to Whonnock. After September, the fishery switches between the standard Chinook net and a chum net that is 6.75 inch mesh. No differentiation between jack Chinook and adult Chinook is made.

In theory, test fishery catch informs species composition through catch-per-unit-effort (CPUE) and an expansion line. The length measurements from the test fishery also inform the species specific mean and standard deviation of lengths.

```{mermaid}
flowchart TD
  A(Hydroacoustic Counts) --> B(Total Salmon)
  A --> C(Stratification Weights)
  C --> D(Hydroacoustic Lengths)
  E(Test Fishery Catch) --> D
```

## Mixture Model for Hydroacoustic Lengths

If we knew that the $i$th measured fish length, $X_i$, belonged to species $k$, $z_i = k$, then we assume that the lengths are normally distributed,

$$X_i|z_i = k \sim  \text{Normal}(\mu_k, \sigma_k^2).$$
Where $\mu_k$ is the mean and $\sigma^2_k$ the variance of the  fork lengths measured in cm without error. Measurements using sonar introduces additional measurement error, $\sigma_0^2$, such that the sonar measured lengths, $x_i$, are normally distributed,

$$x_i |z_i=k \sim  \text{Normal}(\mu_k, \sigma_k^2+\sigma_0^2),$$
with new variance $\sigma_k^2+\sigma_0^2$.

Additionally, due to the physics of how the beam spreads, we expect lengths to be measured with positive bias as the fish gets further from the sonar. For generality, we will call this function $b(r_i)$, and update the mean as a function of range $r_i$,

$$x_i |z_i=k \sim  \text{Normal}(\mu_k + b(r_i), \sigma_k^2+\sigma_0^2).$$
For simplicity, the correction term is assumed linear with respect to the coefficients, with covariates $Y$, that include $\mathbf{r}$,

$$
  b(r_i) = \sum_j \beta_j Y_{ij}.
$$

As species identities are hidden on the sonar, $z_i$ is not observed and instead we marginalize, or sum out, the term from the density. Therefore, the marginal density for a single observation $x_i$, including the stratification weights, $\omega_i = N_i/n_i$, can be written as,
$$
f_{\omega}(x_i) = \Big\{ \sum_{k=1}^K P(z_i = k) f(x_i|z_i = k) \Big\}^{\omega_i},
$$
where $f_\omega$ denotes the weighted form of the probability density. 

The term of interest is the probability that an individual fish belongs to species $k$, $P(z_i = k)$. For a conventional mixture model, it is assumed that $P(z_i = k) = \pi_k$, or the mixture proportions are constant across all observations. However, due to strong heterogeneity in sonar data, the proportions may be varied in response to a set of covariates.
Following a generalized linear model (glm) we use a multivariate-logit link to relate these probabilities to different covariates, $X$, with regression coefficients $\mathbf{\alpha}$,
$$
P(z_i = k) = \frac{\exp(\sum_j X_{ij} \alpha_{kj})}{1+\sum_{l=1}^{K-1}\exp(\sum_j X_{ij} \alpha_{lj})},
$$
for $k < K$. This ensures that $\sum P(z_i = k) = 1$ by setting the $K$th species as $P(z_i = K) = 1-\sum_{k=1}^{K-1} P(z_i = k)$.

### Chinook Lengths

We observe a lot of heterogeneity in Chinook lengths, in particular with how jack Chinook are classified, fork length < 50 cm. In this model, we allow a separate distribution just for Chinook that is it's own mixture model. The population of Chinook lengths are treated as a mixture model with either two or three components, (jack and adult) and (jack, small adult, and large adult) respectively. For simplicity, we treat Chinook as the $K$th species, and $P(z_i = K)$ from above represents the proportion of Chinook generally. Chinook lengths come from a three component Gaussian mixture model, of jack, small adult, and large adult, or two more simply jack and adult. Note that if including small adults, the proportion is held fixed, as it cannot be estimated directly from the data. For a measured length $x_i$, that is Chinook, $z_i = K$, we denote $c_i \in (1,2,3)$ indicating the size class of Chinook, 
$$
  f(x_i|z_i=K) = \sum_{j=1}^3 P(c_i=j|z_i=K) f(x_i|z_i=K, c_i=j).
$$
Here $f(x_i|z_i=K, c_i=j)$ is the normal distribution with mean and variance relating to a Chinook species of size class $j$. Similar to above, we allow the user to model the Chinook proportions according to a set of covariates using a logit-link, to estimate the proportion of jack Chinook,
$$
  P(c_i=j|z_i=K) = \frac{1}{1+\exp(-\sum_j \gamma_{ij}X_{ij})}
$$

### Adjusting Species Lengths

It is not possible to let the model fully fit the mean length of each species, $\mu_k$. However, we know that fish caught in the test fishery may not be fully representative of the size class distribution of the actual fish, such as pink salmon caught in the main stem at Whonnock have been shown to be larger than those caught on a fish wheel near shore. To account for that, we introduce an additional parameter $\delta_k$ which allows us to fit the true species mean length, $\mu_k = \mu_k^(0) + \delta_k$, where $\delta_k \in (-2,2)$, or some upper and lower limits decided by the user in cm.

```{mermaid}
flowchart TD
  A(Hydroacoustic Counts) --> B(Total Salmon)
  A --> C(Stratification Weights)
  C --> D(Hydroacoustic Lengths)
  E(Test Fishery Catch) --> D
  D --> F(Species Proportions)
  B --> F
  E --> G(True Species Lengths)
  G --> D
```

### Key Mixture Model Parameters

1. $\mathbf{\alpha}$ - Estimates the proportion of each species in relation to a set of covariates, which may just include the intercept.
1. $\mathbf{\gamma}$ - Estimates the proportion of Chinook that are jack sized, typically should hold constant across days.
2. $\mathbf{\mu}$ - Generally held fixed (assumed known) based on the test fishery lengths.
3. $\mathbf{\sigma}$ - Generally held fixed (assumed known) based on the test fishery lengths.
4. $\sigma_0$ - Estimated by the model, but also field tested in hydroacoustic experiments with known fish lengths.
5. $\mathbf{\beta}$ - Lengths bias due to beam spreading. This is often going to be $\mu_{ki} = \mu_k + \beta_0 + \beta_1 r_i$, but may also be $\mu_{ki} = \mu_k + \beta_{bin_i}$, where $bin_i$ is the sonar bin (Bin 1 = 0-10 m) and (Bin 2 = 10-20 m). Estimates of this are also taken from experiments but fitted in the model.
6. $\mathbf{\delta}$ - The difference from the test fishery observed mean, bounded by some amount chosen by the user (e.g. $\delta_1 \in (-2,2)$).


## Test Fishery Catch Model

In version 1 of this model, we assumed that the test fishery catch $\mathbf{n}_i = (n_{i1}, \ldots, n_{iK})$, was multinomial distributed, conditional on the total catch, $C_i = \sum_k n_{ik}$,
$$
  \mathbf{n}_i \sim \text{Multinomial}(\mathbf{p}_i, C_i),
$$
where $p_{ik} = \frac{q_k \pi_k}{1+\sum_{l<K} q_l \pi_l}$. In theory, if we know relative catchability, $\mathbf{q}$, then this can help to inform the species composition, or $\mathbf{\pi}$. However, due to the variability of $q_k$ in response to fishing and the environment, combined with losing information about relative abundance by conditioning on $C_i$, we have moved away from this. Instead, we will use expansion lines for each test fishery species and mesh type, $1/q_i$ and write,
$$
  n_{ik} \sim \text{Poisson}(\pi_k N e_i/q_i),
$$
where $e_i$ is the test fishing effort $e_i = \frac{\Delta(t_i) L_i}{1000}$, with $L_i$ equal to the next length in fathoms and $\Delta(t_i)$ equal to the fishing time. The advantage here is that if we know that the relative total abundance of Chinook based on historical CPUE expansion lines, then this makes sure that our estimate of species composition $\pi_K$ stays in that ball park, using the length data to correct that. We can also weight the density to change its relative importance $f_{w}(n_{ik}) = f(n_{ik})^{w_i}$, with user supplied weights $\mathbf{w}$.

The new parameters that are estimated with the test fishery data is $\mathbf{e} = 1/\mathbf{q}$, which typically will include Whonnock sockeye and Chinook (variable mesh net), as well as Albion Chinook (variable mesh net, Chinook net, and chum net).

```{mermaid}
flowchart TD
  A(Hydroacoustic Counts) --> B(Total Salmon)
  A --> C(Stratification Weights)
  C --> D(Hydroacoustic Lengths)
  E(Test Fishery Catch) --> D
  D --> F(Species Proportions)
  B --> F
  E --> G(True Species Lengths)
  G --> D
  E --> H(Catchability)
  H --> F
```

## Penalized Pseudo-Likelihood

The model presented here with stratification weights is not a proper likelihood function. Instead, using the weights it becomes a pseudo-likelihood that holds similar properties of the likelihood. Many of the parameters we are estimating are known to some degree, such as at Whonnock has historical expansion line estimates, $e = 1/q$, for sockeye that they update weekly. In this case, we may either choose to fix this parameter in the model, or fit it constrained by prior information. A penalized likelihood is when we choose a term to ensure that $e$ stays relatively close to some value, e.g. $e \sim \text{Normal}(3000, 500)$. However, if we want to treat it as a proper prior distribution, then we would be finding the posterior mode and require a Jacobian transformation as we do computation on $log(e_i)$. The user may choose whether or not to include the Jacobian, but we typically suggest to such that $\log(e_i) \sim N(3000, 500) e_i$.

In testing, standardize prior (penalty) distributions (functions) will be set as default in the package, with the user able to update those values based on in-season realities.

## Model Fitting

Direct maximization of mixture models can be challenging due to a multimodal likelihood. Instead, we employ the expectation-maximization (EM) algorithm. This is a two-step algorithm written in R package RTMB. Note that with minor changes, this model could be fitted with HMC in a Bayesian framework.

If we reintroduce the $z_i$ term as an augmented variable then given a set of parameter values from iteration $t-1$ of the algorithm, we know that the posterior $z_i|x_i$ is
$$
P_{(t)}(z_i = k|x_i) = \frac{P_{(t-1)}(z_i = k) f_{(t-1)}(x_i|z_i = k)}{\sum_{k=1}^K P_{(t-1)}(z_i = k) f_{(t-1)}(x_i|z_i = k)},
$$
where ${(t-1)}$ indicates the function is evaluated at parameter values from the time step $t-1$ of the algorithm. Once we have evaluated the posterior probabilities given the current state of the algorithm, we then compute the objective function $Q_t(\mathbf{\theta}_t|\widehat{\mathbf{\theta}}_{t-1})$, for the parameters $\mathbf{\theta}$,

$$
\begin{align}
  Q(\mathbf{\theta}_t|\widehat{\mathbf{\theta}}_{t-1})  &= \sum_{i=1}^n \mathbb{E}_{z_i|\widehat{\mathbf{\theta}}_{t-1}}\log\{f_\omega(x_i)\},\\
&= \sum_{i=1}^n \sum_{k=1}^K \omega_i[\log\{P(z_i=k)\} + log\{f(x_i|z_i=k)\}] P_{(t)}(z_i = k|x_i).
\end{align}
$$
For each $t$, we find $\widehat{\mathbf{\theta}}_t = \text{argmax}_{\mathbf{\theta}_t} Q(\mathbf{\theta}_t|\widehat{\mathbf{\theta}}_{t-1})$ until the pesudo log-likelihood between each iteration stays approximately equal to some small threshold value.

When adding the test fishery count data, we update our objective function to also fit the other terms, $O$,
$$
   O(\mathbf{\theta}_t|\widehat{\mathbf{\theta}}_{t-1}) = Q(\mathbf{\theta}_t|\widehat{\mathbf{\theta}}_{t-1}) + \log(f_w(\mathbf{n})).
$$
Fitting should take several seconds and is typically set to a maximum of 1000 iterations. If convergence isn't found, then it is likely that the model is poorly set up and covariates should be changed, or prior/penalty terms. The algorithm operates until the maximum number of iterations, or the tolerance between changes to the psuedo-likelihood between iterations meets some user provided threshold (default = $1e^-8$).

