---
title: "Species Composition Workflow"
author: "Paul van Dam-Bates"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
description: >
  An overview of how to estimate species composition using `SonarSpeciesComp`.
format: 
  html:
    embed-resources: true
    theme: cosmo
vignette: >
  %\VignetteIndexEntry{Custom HTML Vignette}
  %\VignetteEngine{quarto::format}
  %\VignetteEncoding{UTF-8}
---

## Data Types

### Hydroacoustic Counts

Every hour hydroacoustic counts are taken in each sonar bin using an ARIS 1800. At Qualark the sonar is rolled 35 degrees to be able to enumerate all fish along a steep bank. At Mission, the right bank is relatively flat and a single aim with no roll is sufficient for full coverage. However, on the left bank, two aims are used within the first 10 m to enumerate all fish. At both sites, counts are done by bank, and 10 m distance bins. Qualark completes counts out to 30 m, or 3 bins on each bank, and Mission out to 50 m. Counts are labelled as Up and Down for the number of fish counted as swimming upstream or down stream. Total salmon then is the number of fish migrating upriver, accounting for potential double counts by subtracting the down stream counts. The counts also inform the stratification weights from the stratified length measurements which we will describe next.

```{mermaid}
flowchart TD
  A(Hydroacoustic Counts) --> B(Total Salmon)
  A --> C(Stratification Weights)
```

### Hydroacoustic Lengths

At Mission, hydroacoustic lengths are taken for 20 fish, every three hours in each sonar Aim, Bin, and Bank. Sonar bins 1-3 are measured, with distances further than that unreliable for length measurement. Similarly, at Qualark, measurement lengths follow the same process but for 2 distance bins, and a single aim due to a target roll angle of 35 degrees. Updates to the sampling protocols will be trialed in 2026. Due to beam spreading, bin 3 will no longer be measured with effort distributed across the closer bins to improve precision.

A randomly chosen fish migrating past the monitoring station does not have an equal chance of being measured. Instead, due to the stratified design, fish that correspond to a high migration period are less likely to be observed than those in low migration. If 20 fish pass by and 20 are measured, then they are all measured with probability 1. If 100 fish pass by in the same period, and 20 are selected, then they are measured with probability 20/100. The number of fish that are passing by are measured during the corresponding sonar count ($N_i$). As a result, the inclusion probability $\pi_i = n_i/N_i$, where $n_i$ is the number of lengths taken, generally 20.

```{mermaid}
flowchart TD
  A(Hydroacoustic Counts) --> B(Total Salmon)
  A --> C(Stratification Weights)
  C --> D(Hydroacoustic Lengths)
```

### Hydroacoustic Lengths

At Mission, the Whonnock test fishery operates just downstream of the site. A gillnet does two sets at the daytime high tide (targets the larger tide) for 30 minutes each. The number of sockeye, pink salmon, jack Chinook and adult Chinook are counted as either gilled or tangled. Additionally, fork lengths are also recorded. DFO also operates a Chinook focused fishery at Albion that also does two sets, changing the net type every day between a "standard" Chinook net constructed using 8 inch mesh and a "multi-panel" net consisting of panels of 6, 7, 8, and 9 inch mesh. After September, this fishery switches between the standard Chinook net and a chum net that is 6.75 inch mesh. No differentation between jack Chinook and adult Chinook is made.

At Qualark, a test fishery operates directly in front of the hydroacoustic station on the right bank. In the morning, three sets are completed of increasing mesh size (4.75, 5.75, 8 inch) in the morning and (4, 5.25, 6.75 inch) in the evening. Fish occurs for approximately 5 minutes for each set and similarly to Whonnock, fork lengths are recorded.

In theory, test fishery catch informs species composition through catch-per-unit-effort (CPUE) and an expansion line. The length measurements from the test fishery also inform the species specific mean and standard deviation of lengths.

```{mermaid}
flowchart TD
  A(Hydroacoustic Counts) --> B(Total Salmon)
  A --> C(Stratification Weights)
  C --> D(Hydroacoustic Lengths)
  E(Test Fishery Catch) --> D
```

## Mixture Model for Hydroacoustic Lengths

If we knew that the $i$th measured fish length $x_i$ belonged to species $k$, $z_i = k$, then 

$$x_i|z_i = k \sim  Normal(\mu_k, \sigma_k^2).$$

With species specific mean, $\mu_k$, and variance $\sigma^2_k$. However, there is additional measurement error introduced by the sonar measurement, $\sigma_0^2$,

$$x_i |z_i=k \sim  Normal(\mu_k, \sigma_k^2+\sigma_0^2).$$
Additionally, due to the physics of how the beam spreads, we expect the mean to be reduced by some function of distance from the sonar, $\beta(r_i)$,

$$x_i |z_i=k \sim  Normal(\mu_k + \beta(r_i), \sigma_k^2+\sigma_0^2).$$

To add another complication, the roll angle (35 degrees) at Qualark changes the way the fish is viewed and measured on the sonar. This has the impact of the fork length $x_i = x_i'/cos(35) \approx 1.22 x'_i$, where $x'_i$ is the measured lengths. 

Note that we do not actually observe $z_i = k$ and therefore must marginalize the term from the density. Therefore, the marginal density for a single observation $x_i$, including the stratification weights, $\omega_i = N_i/n_i$, can be written as,
$$
f(x_i) = \Big\{ \sum_{k=1}^K P(z_i = k) f(x_i|z_i = k) \Big\}^{\omega_i}.
$$
The term of interest is the probability that an individual fish belongs to species $k$, $P(z_i = k)$. In typical mixture modeling, we may assume these are constant across the population, $P(z_i = k) = \pi_k$. However, here we will generalize to allow for a multivariate-logit link to relate these probabilities to different covariates, $X$, with regression coefficients $\mathbf{\alpha}$,
$$
P(z_i = k) = \frac{\text{exp}(X_{i} \mathbf{\alpha}_{k})}{1+\sum_{l=1}^{K-1}\text{exp}(X_{i} \mathbf{\alpha}_{l})},
$$
for $k < K$. This ensures that $\sum P(z_i = k) = 1$ by $P(z_i = K) = 1-\sum_{k=1}^{K-1} P(z_i = k)$.

Key parameters:

1. $\mathbf{\alpha}$ - Estimates the proportion of each species in relation to a set of covariates, which may just include the intercept.
2. $\mathbf{\mu}$ - Generally held fixed (assumed known) based on the test fishery lengths.
3. $\mathbf{\sigma}$ - Generally held fixed (assumed known) based on the test fishery lengths.
4. $\sigma_0$ - Estimated by the model, but also field tested in hydroacoustic experiments with known fish lengths.
5. $\mathbf{\beta}$ - Lengths bias due to beam spreading. This is often going to be $\mu_{ki} = \mu_k + \beta_0 + \beta_1 r_i$, but may also be $\mu_{ki} = \mu_k + \beta_{bin_i}$, where $bin_i$ is the sonar bin (Bin 1 = 0-10 m) and (Bin 2 = 10-20 m). Estimates of this are also taken from experiments but fitted in the model.

### Chinook Lengths

We observe a lot of heterogeneity in Chinook lengths, in particular with how jack Chinook are classified, a measured Chinook length < 50, or arbitrary cut-off. Instead, we can allow a separate distribution just for Chinook that is a mixture of on it's own. In this case, we introduce a nested mixture model that has a fixed length and proportion for small adult vs large adult based on the test fishery, as well and an either fixed proportion, or fitted, for jack Chinook. In this case, the $\alpha$ terms estimate the proportion of Chinook, and we introduce an additional term $\mathbf{\gamma} = (\gamma_1, \gamma_2, \gamma_3)$ that is the proportion of jack Chinook, small adult Chinook, and large adult Chinook respectively. Note that if we will typically hold $\gamma_2$ fixed, as it cannot be estimated directly from the data. Then for a measured value that is $z_i = K$, Chinook, with $c_i \in (1,2,3)$ indicating the size class of Chinook, 
$$
  f(x_i|z_i=K) = \sum_{j=1}^3 P(c_i=j|z_i=K) f(x_i|z_i=K, c_i=j).
$$
Note that $f(x_i|z_i=K, c_i=j)$ is the normal distribution with mean and variance relating to a Chinook species of size class $j$.

### Adjusting Species Lengths

It is not possible to let the model fully fit the mean length of each species, $\mu_k$. However, we know that fish caught in the test fishery may not be fully representative of the size class distribution of the actual fish, such as pink salmon caught in the main stem at Whonnock have been shown to be larger than those caught on a fish wheel near shore. To account for that, we introduce an additional parameter $\delta_k$ which allows us to fit the true species mean length, $\mu_k = \mu_k^(0) + \delta_k$, where $\delta_k \in (-2,2)$, or some upper and lower limits decided by the user in cm.

```{mermaid}
flowchart TD
  A(Hydroacoustic Counts) --> B(Total Salmon)
  A --> C(Stratification Weights)
  C --> D(Hydroacoustic Lengths)
  E(Test Fishery Catch) --> D
  D --> F(Species Proportions)
  B --> F
  E --> G(True Species Lengths)
  G --> D
```

## Model Fitting

Direct maximization of mixture models can be challenging due to a multimodal likelihood. Instead, we employ the expectation-maximization (EM) algorithm. This is a two-step algorithm written in RTMB in R.

We introduce the $z_i$ term back as an augmented variable. Given a set of parameter values from iteration $t-1$ of the algorithm, we know that the posterior $z_i|x_i$ is
$$
P_{(t)}(z_i = k|x_i) = \frac{P_{(t-1)}(z_i = k) f_{(t-1)}(x_i|z_i = k)}{\sum_{k=1}^K P_{(t-1)}(z_i = k) f_{(t-1)}(x_i|z_i = k)},
$$
where ${(t-1)}$ indicates the function is evaluated at parameter values from the time step $t-1$ of the algorithm. Once we have evaluated the posterior probabilities given the current state of the algorithm, we then compute the objective function $Q_t(\mathbf{\theta}_t|\widehat{\mathbf{\theta}}_{t-1})$, for the parameters $\mathbf{\theta}$,

$$
\begin{align}
  Q(\mathbf{\theta}_t|\widehat{\mathbf{\theta}}_{t-1})  &= \sum_{i=1}^n \mathbb{E}_{z_i|\widehat{\mathbf{\theta}}_{t-1}}log\{f(x_i)\},\\
&= \sum_{i=1}^n \sum_{k=1}^K \omega_i[log\{P(z_i=k)\} + log\{f(x_i|z_i=k)\}] P_{(t)}(z_i = k|x_i).
\end{align}
$$
Iteratively, we find $\widehat{\mathbf{\theta}}_t = \text{argmax}_{\mathbf{\theta}_t} Q(\mathbf{\theta}_t|\widehat{\mathbf{\theta}}_{t-1})$ until the log-likelihood between each iteration stays approximately equal to some small threshold value.

## Test Fishery Catch Model

In version 1 of this model, we assumed that the test fishery catch $\mathbf{c}_i = (c_{i1}, \ldots, c_{iK})$, was multinomial distributed, conditional on the total catch, $C_i = \sum_k c_{ik}$,
$$
  \mathbf{c}_i \sim Multinomial(\mathbf{p}_i, C_i),
$$
where $p_{ik} = \frac{q_k \pi_k}{1+\sum_{l<K} q_l \pi_l}$. In theory, if we know relative catchability, $q$, then this can help to inform the species composition, or $\mathbf{\pi}$. However, due to variabilty of $q_k$, and losing information about relative abundance of some species we have moved away from this. Instead, we will use expansion lines for each test fishery species $1/q_k$ and write,
$$
  c_{ik} \sim Binomial(\pi_k N, q_k e_i),
$$
where $e_i$ is the test fishing effort $e_i = \frac{\Delta_i L_i}{1000}$, with $L_i$ equal to the next length in fathoms and $\Delta_i$ equal to the fishing time. The advantage here is that if we know that the relative total abundance of Chinook based on historical CPUE expansion lines, then this makes sure that our estimate of species composition $\pi_K$ stays in the correct ball park. We can also weight this portion of the likelihood to change its relative importance.

```{mermaid}
flowchart TD
  A(Hydroacoustic Counts) --> B(Total Salmon)
  A --> C(Stratification Weights)
  C --> D(Hydroacoustic Lengths)
  E(Test Fishery Catch) --> D
  D --> F(Species Proportions)
  B --> F
  E --> G(True Species Lengths)
  G --> D
  E --> H(Catchability)
  H --> F
```

## Penalized Likelihood

Many of the parameters we are estimating are known to some degree, such as at Whonnock they have an expansion line, $1/q_k$, for sockeye that they update weekly. In this case, we may either choose to fix this parameter, or fit it constrained by the prior information. A penalized likelihood is when we choose a term to ensure that $q_k$ stays relatively close to some value, e.g. $q_k \sim N(1/3000, 0.1)$. However, if we want to treat it as a proper prior distribution, then we would be finding the posterior mode and require a Jacobian transformation as we do computation on $log(q_i) \sim N(1/3000, 0.1)/q_i$.
